WFLAGS = -W -Wall -Wshadow -pedantic -lwiringPi -lpthread -lm
sensorOriginal: sensorOriginal.c
	gcc $(WFLAGS) -o sensorOriginal.out sensorOriginal.c
	./sensorOriginal.out

sensor2: sensor2.c
	gcc $(WFLAGS) -o seclean:
	rm -f *.o *.outnsor2.out sensor2.c
	./sensor2.out

clean:
	rm -f *.o *.out